spring.application.name=crudapi

#port
server.port=8084

#Database conection
spring.datasource.url=jdbc:mysql://localhost:3306/crud_spring
spring.datasource.username=root
spring.datasource.password=

#logs
logging.level.org.springframework.web=DEBUG
