spring.application.name=crudapi

#port
server.port=8084

#Database conection
spring.datasource.url=jdbc:mysql://localhost:3306/crud_spring
spring.datasource.username=root
spring.datasource.password=

#jwt
jwt.secret=MiClaveSuperSecretaParaPruebas123456789
jwt.expiration=86400000

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.scalar.enabled=true


#logs
logging.level.org.springframework.web=DEBUG
